config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:index,:show] do
    resources :posts, only: [:index,:new,:create,:show ]
  end

  resources :posts do
    resources :comments, only: [:new, :create]
    resources :likes, only: [:create]
  end
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_many :comments
  has_many :likes

  validates_presence_of :title
  validates :title, length: { maximum: 250 }

  after_create :update_user_post_count
  after_create :recent_comments

  def update_user_post_count
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates_presence_of :name
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :recent_posts

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :posts_counter, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :posts_counter, :email, :password, :current_password)
    end
  end

  # private

  # def after_sign_out_path_for(resource_or_scope)
  #   new_user_session_path
  # end

  # def after_sign_in_path_for(resource)
  #   # Customize the path you want to redirect to after successful sign-in
  #   users_path
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @comment = Comment.new
  end

  def create
    @current = current_user
    @post = Post.find(params[:post_id])
    @new_comment = @post.comments.build(text: comment_parameters[:text], user_id: @current.id)
    respond_to do |format|
      format.html do
        if @new_comment.save
          redirect_to user_post_path(current_user, @post), notice: 'Comment created successfully'
        else
          redirect_to user_post_path(current_user, @post), alert: 'Comment not created successfully'
        end
      end
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def create
    @current = current_user
    @post = Post.find(params[:post_id])
    @like = @post.likes.build(user_id: @current.id)

    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_path(current_user, @post), notice: 'you liked the post'
        else
          redirect_to user_post_path(current_user, @post), alert: 'unable to like'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])
    @current = current_user
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @new_post = current_user.posts.build(post_parameters)
    respond_to do |format|
      format.html do
        if @new_post.save
          redirect_to user_post_path(current_user, @new_post), notice: 'Post was successfully created.'
        else
          flash.now[:alert] = 'Post could not be created. Please try again.'
          render :new
        end
      end
    end
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<div id="comment">
    <%=comment.user.name%>: <%= comment.text %>
</div>

app/views/comments/_create.html.erb
<%= form_with model: [@user, @post, @comment], class: "form", scope: :comment do |f| %>
  <section class="form-section">
    <%= f.text_area :text,
    placeholder: "Write a comment...", 
    required: true,
    class: "text_input" %>
  </section>

  <section class="form-section">
    <%= f.submit "Comment", class: "submit_button" %>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>

  </body>
</html>

app/views/likes/_create.html.erb
<%= form_with model: [@post, @like], url: post_likes_path(@post), class: "form", scope: :like do  |f| %>
<%f.submit "like", class: "submit_button"%>
<%end%>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<div id="post">
post #<%= post.id %><br>
    <%= post.text %><br>
<p id= "comments-likes">
comments: <%= post.comments_counter? ? post.comments_counter : 0 %> , 
Likes: <%= post.likes_counter? ? post.likes_counter : 0 %>
</p>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<nav class="nav">
    <%= link_to "Add New Post", new_user_post_path(@user.id) %>
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
     <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>
<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <%= value %>
  </div>
<% end %>
<%= render @user%>
<% @posts.each do |post| %>
    <a href ="<%= user_post_path(@user, post)%>"><%= render post%></a>
    <%= "no comments for this post" if post.comments.empty?%>
    <div class="comments">
    <% post.recent_comments.includes(:user).each do |comment|%>
        <%=render comment%>
    <% end %>
    </div>
    <p id="view-post"><%= link_to 'View Post', user_post_path(@user, post) %></p>
<% end %>
</body>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<h1>Add a new post</h1>
<%= form_with model: @post, url: user_posts_path(@user), method: :post, local: true, scope: :post do |form| %>
   <%= form.label :title %>
  <%= form.text_field :title, required: true %>

  <%= form.label :text %>
  <%= form.text_area :text, required: true %>

  <%= form.submit "Create Post" %>
<% end %>
</body>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<body>
<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <%= value %>
  </div>
<% end %>
<nav class="nav">
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
     <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>
<%= render partial: 'post', locals: { post: @post } %> <br>
<%= "no comments for this post" if @post.comments.empty?%>
<div class="comments">
<% @post.comments.each do |comment|%>
        <%=render comment %>
<% end %>
</div>

<div class="like-comment"><%= render "comments/create" %> 

<%if Like.where(user_id: User.first.id, post_id: @post.id).exists?%>
 <p id= "liked">Liked<p>
<%else%>
<%= render "likes/create" %></div>
<%end%>
</body>

app/views/users/_user.html.erb
<header>
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</header>
<body>
<div id="user"> 
  <img id="user-image" src="<%= user.photo %>" alt="User Photo">
  <article id="user-details">
    <h1><%= user.name %></h1>
    <p>Number of posts: <%= user.posts_counter.nil? ? 0 : user.posts_counter %></p>
  <article>
</div>
</body>

app/views/users/index.html.erb
<nav class="nav">
  <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
  <%= link_to 'Sign Up', new_user_registration_path %>
</nav>
<%"No users" if @users.empty?%>
<% @users.each do |user| %>
    <a href="<%= user_path(user) %>"><%= render user%></a>
    <br>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
<nav class="nav">
    <%= link_to "Add New Post", new_user_post_path(@user.id) %>
    <%= link_to "Home", root_path %>
    <%= link_to "Back", :back %>
    <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
</nav>

<%= render @user%>

<div id="bio">
 Bio: <%= @user.bio %>
 </div>
<br>
<%='No posts for this user' if (@user.posts.empty?) %>
<% @user.recent_posts.each do |post| %>
   <a href ="<%= user_post_path(@user, post)%>">
  <%= render post %>
<% end %>
<div class="button-container">
    <button><a href="<%= user_posts_path(@user) %>">See all posts</a></button>
</div>
</body>